server:
  port: 50005
spring:
  application:
    name: springCloud-monitor
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://springCloud-eureka1:50001/eureka/,http://springCloud-eureka2:50002/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false